import { Injectable, ForbiddenException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { BaseService, FindManyOptions, FindManyResult } from '@hydrabyte/base';
import { RequestContext, PredefinedRole } from '@hydrabyte/shared';
import { Signal } from './signal.schema';
import { Account } from '../account/account.schema';

@Injectable()
export class SignalService extends BaseService<Signal> {
  constructor(
    @InjectModel(Signal.name) signalModel: Model<Signal>,
    @InjectModel(Account.name) private readonly accountModel: Model<Account>,
  ) {
    super(signalModel as any);
  }

  private isOrgOwner(context: RequestContext): boolean {
    return (
      context.roles?.includes(PredefinedRole.OrganizationOwner) ||
      context.roles?.includes(PredefinedRole.UniverseOwner)
    );
  }

  /**
   * Signals are generated by SYSTEM_CONTEXT (owner.orgId = 'system', owner.userId = 'system').
   * BaseService's owner-scoping (filter by owner.orgId) would return 0 results for real users.
   * We must bypass BaseService for user queries and scope by accountId instead.
   */
  private isSystemContext(context: RequestContext): boolean {
    return context.userId === 'system' && context.orgId === 'system';
  }

  private async getUserAccountIds(userId: string): Promise<Types.ObjectId[]> {
    return this.accountModel
      .find({ 'owner.userId': userId, isDeleted: false })
      .distinct('_id');
  }

  private async getOrgAccountIds(orgId: string): Promise<Types.ObjectId[]> {
    return this.accountModel
      .find({ 'owner.orgId': orgId, isDeleted: false })
      .distinct('_id');
  }

  async findAll(options: FindManyOptions, context: RequestContext): Promise<FindManyResult<Signal>> {
    // SYSTEM_CONTEXT (used by workers for generation/expiry) — use default BaseService logic
    if (this.isSystemContext(context)) {
      return super.findAll(options, context);
    }

    // For real users: scope signals by accountId (not owner.orgId which is 'system')
    let accountIds: Types.ObjectId[];
    if (this.isOrgOwner(context)) {
      // OrgOwner sees signals for all accounts in their org
      accountIds = await this.getOrgAccountIds(context.orgId);
    } else {
      // Regular user sees signals for their own accounts only
      accountIds = await this.getUserAccountIds(context.userId);
    }

    // Validate requested accountId belongs to accessible accounts
    const requestedAccountId = (options.filter as any)?.accountId;
    if (requestedAccountId) {
      const requested = new Types.ObjectId(requestedAccountId);
      const belongs = accountIds.some((id) => id.equals(requested));
      if (!belongs) {
        // Return empty — requested accountId not accessible
        options.filter = { ...(options.filter || {}), accountId: new Types.ObjectId() };
      } else {
        // Convert string → ObjectId so MongoDB query matches correctly
        options.filter = { ...(options.filter || {}), accountId: requested };
      }
    } else {
      options.filter = { ...(options.filter || {}), accountId: { $in: accountIds } };
    }

    // Query directly — bypass BaseService owner-scoping (which would filter by owner.orgId = 'system')
    const notAllowedFilters = ['isDeleted', 'deletedAt', 'owner', 'sort', 'sortOrder', 'sortBy', 'page', 'limit'];
    const { sort, page = 1, limit = 10 } = options;
    const filter: any = options.filter ? { ...(options.filter as any) } : {};
    notAllowedFilters.forEach((f) => delete filter[f]);
    for (const key in filter) {
      if (filter[key] === '' || filter[key] === null) delete filter[key];
    }
    delete filter.selectFields;
    delete filter.statisticFields;
    filter.isDeleted = false;

    const [data, total] = await Promise.all([
      (this as any).model
        .find(filter)
        .sort(sort)
        .skip((page - 1) * limit)
        .limit(limit)
        .select('-isDeleted -deletedAt -password -createdBy -updatedBy')
        .exec(),
      (this as any).model.countDocuments(filter).exec(),
    ]);

    return {
      data,
      pagination: { page, limit, total },
      statistics: { total },
    };
  }

  async findById(id: any, context: RequestContext): Promise<Partial<Signal>> {
    // SYSTEM_CONTEXT — use default BaseService logic
    if (this.isSystemContext(context)) {
      return super.findById(id, context);
    }

    // Fetch signal directly without owner-scoping (bypassing BaseService)
    const signal = await (this as any).model
      .findOne({ _id: id, isDeleted: false })
      .select('-isDeleted -deletedAt -password -createdBy -updatedBy')
      .exec();

    if (!signal) {
      throw new ForbiddenException('Signal not found or access denied');
    }

    if (this.isOrgOwner(context)) {
      // OrgOwner: verify signal's account belongs to org
      const account = await this.accountModel.findOne({
        _id: signal.accountId,
        'owner.orgId': context.orgId,
        isDeleted: false,
      });
      if (!account) {
        throw new ForbiddenException('Access denied');
      }
    } else {
      // Regular user: verify signal's accountId belongs to user
      const accountIds = await this.getUserAccountIds(context.userId);
      const belongs = accountIds.some((aid) => aid.equals(signal.accountId as Types.ObjectId));
      if (!belongs) {
        throw new ForbiddenException('Access denied');
      }
    }

    return signal;
  }
}
